### ISSUE TITLE
wmic is depricated in Window's from Win10 on...

### ISSUE THREAD

**Issue by TechKen1** [w-e-w/stable-diffusion-webui-GPU-temperature-protection#8]
When GPU temp protection starts, I get the following error in my command prompt window...

"'wmic' is not recognized as an internal or external command, operable program or batch file."

wmic has been depricated by windows since win10 - 21H1. It is also now disabled by default in Win11, in preperation for complete removal of wmic.

Microsoft recommends using using Power Shell CIM cmdlets instead to access WMI.

**Comment by w-e-w** [comment]
Thanks

**Comment by w-e-w** [comment]
I made a fix can you test
- https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/pull/7
> works on my system but like to verify

**Comment by TechKen1** [comment]
new error... lol 

*** Error loading script: gpu_temperature_protection.py
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd.webui\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1017, in get_code
      File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd.webui\webui\extensions\stable-diffusion-webui-GPU-temperature-protection\scripts\gpu_temperature_protection.py", line 109
        <title>stable-diffusion-webui-GPU-temperature-protection/scripts/gpu_temperature_protection py at restructure · w-e-w/stable-diffusion-webui-GPU-temperature-protection</title>
                                                                                                                      ^
    SyntaxError: invalid character '·' (U+00B7)

it's the character between the word "restructure" and "w-e-w" in the title section.  Testing my copy and will edit if it works.

**Comment by TechKen1** [comment]
removed the invalid character, and cleared that error, but now I'm getting this one...

*** Error loading script: gpu_temperature_protection.py
    Traceback (most recent call last):
      File "E:\sd.webui\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd.webui\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1017, in get_code
      File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd.webui\webui\extensions\stable-diffusion-webui-GPU-temperature-protection\scripts\gpu_temperature_protection.py", line 7
        <!DOCTYPE html> (if it's hiding, the carat is on the open tag of !doctype)
        ^
    SyntaxError: invalid syntax

**Comment by w-e-w** [comment]
I saw your account was created on 2015 so I you assume that you have at least a little bit of programming experience I was very wrong

view-source:https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/blob/main/scripts/gpu_temperature_protection.py 
![image](https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/assets/40751091/252a0be9-bfe0-43ac-9a72-748b3b2c1a25)

I believe what you have done is literally download the HTML of the GitHub web page and then try to run it as a Python script

~~oh my ............ you don't do that, why would you like to do that???????~~

----

I'm just going to make the fix
- https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/pull/7

you can completely delete and reinstall reinstall the extension normally in the UI
see if it works

**Comment by TechKen1** [comment]
well, you're both right and wrong. I DO have some programming experience. but I'm 62 now, and haven't done any except playing in bat files since 2010 due to a disability. memory is WAY fallible when it comes to this stuff.  But thanks for being "kind" in how you put it. was appreciated.

**Comment by w-e-w** [comment]
fair and sorry
but it was way too funny of a thing that I have seen in a long while for me not to say that

I should have given clear instructions on how you should try the update version

I truly thought you would know how to do so based on the account age and the good bug report

> for future reference if you need to try a branch, you should be able to use `git` to `fetch` and `switch` the branch of code

> as I have pushed the changes to the main branch and it will be updated / installed by default you don't need to to anything special 

any way

I believe that you have deleted and reinstalled the extensions and it is working?

**Comment by TechKen1** [comment]
Working like an absolute champ!  Thank you, and I'm glad I could at least contribute with informing you of the problem.  :)

used to work for EA (pre-sports) as a print driver tester.  Most of my coding was done REwriting or creating new drivers for printers in the 80's, or writing custom code for sucking data from unix and such over to Windows.  Not quite the same as this. although, I DID get a degree that included html, java and ect, I've forgotten most of it. lol

**Comment by w-e-w** [comment]
> EA (pre-sports)

![image](https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/assets/40751091/0864c90c-7b5f-4269-8904-cc92d56c1bd9)
wow that's really long ago

> REwriting or creating new drivers for printers

that sounds hard,  I know next to nothing about driver level stuff
and maybe it's a different world back then but I couldn't imagine why agame develops and publishes would need someone to write printer drivers in house

>  I'm glad I could at least contribute with informing you of the problem. :)

yes that really helps most of the extensions I write I wrote for others I don't use myself so unless someone reports an issue I literally wouldn't know

to be honest even now I'm still quite mystified on why would someone use this extension
there are far better ways of keeping your GPU temperature under control, and not use something like this a sort of "emergency brake"

**Comment by TechKen1** [comment]
Unfortunately, I'm using a RTX-3060, so an aio water cooler system isn't available for it, I'd need at least a 3080 to get something that would do the job. As for most other solutions, It's plugged into a mini ITX MB. so there are LITERALLY no other slots for air coolers. And it only has two fan's exposed to the outside, other than the one on the RTX. An 80 mm one on the back of the chassis (air out) and a 120 mm in the top of the case (air in). So it's a bit of an issue at times.  I end up pushing over 90+C on any batch size larger than 4. Kinda makes training a bit difficult.  (it's one of the original HP Omen series computers...)  LOL

**Comment by w-e-w** [comment]
you could undervote or limit your gpu clock speed
underworld when done well is quite stable so that's basically free thermal head room
limiting the clock speed does reduce performance, but if you're willing to literally pause the execution you're not missing the performance in the first place

because of how these days they (manufacturers) tune the clock speed and voltage curve and how hard that push things
it is quite likely if you limited the clock speed by 10%, you may be able to keep your temperature well in control
no you can run everything constantly at 90% as opposed to having to run something at 100% And then stop more than 10% of the time
which Nets you more performance

**Comment by TechKen1** [comment]
I'll look at it. See if that helps any doing a speed throttle instead of a temp pause.

**Comment by TechKen1** [comment]
you should have seen/heard when I was using my gtx-1080ti to do this stuff... SHIT! it was like an extra heater in my living room, but one with a damn loud fan in it. lol

**Comment by w-e-w** [comment]
> it was like an extra heater 

I am fortunate enough to have a 3090 (got it used) so I know what you're saying

[3060 170W](https://www.techpowerup.com/gpu-specs/geforce-rtx-3060-12-gb.c3682) 
[1080Ti 250W](https://www.techpowerup.com/gpu-specs/geforce-gtx-1080-ti.c2877) 
[3090 350W](https://www.techpowerup.com/gpu-specs/geforce-rtx-3090.c3622)
[4090 450W](https://www.techpowerup.com/gpu-specs/geforce-rtx-4090.c3889)
>note: take the TDP with a bucket of seawater

on top of that that my CPU is a 13700k, I think it can draw like 250 Max

> normally you won't see maximum CPU and GPU load at the same time unless you're doing synthetic benchmarks

**Comment by TechKen1** [comment]
I actually have both the 3060 AND the 1080. 420w tdp total. Talk about
frying eggs for breakfast... lol
